name: Go CI

on: [push, pull_request]

env:
  MONGODB_VERSION: 4.4.1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Start MongoDB container
      run: |
        make start-mongodb

    - name: Install dependencies
      run: |
        go mod download

    - name: Test
      run: |
        go test ./...

    - name: Stop MongoDB container
      run: |
        docker stop open-blogger_mongodb_1
        docker rm open-blogger_mongodb_1
