name: Go CI

on: [push, pull_request]

env:
  MONGODB_VERSION: 4.4.1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x

    - name: Create mongo Docker container
      uses: DigiPie/mongo-action@v2.0.0
      with:
        image_version: latest
        port: 27017

    - name: Start MongoDB container
      run: |
        make start-mongodb

    - name: Wait for MongoDB to start
      run: |
        until docker exec mongodb mongo --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' &>/dev/null; do
          echo 'Waiting for MongoDB to start...'
          sleep 1
        done

    - name: Install dependencies
      run: |
        go mod download

    - name: Test
      run: |
        go test ./...

    - name: Stop MongoDB container
      run: |
        docker stop mongodb
        docker rm mongodb
